### ISSUE TITLE
`select` not placing what's selected in yank register

### ISSUE THREAD

**Issue by sf8193** [AckslD/nvim-neoclip.lua#101]
config
```
use {"AckslD/nvim-neoclip.lua", requires = {{'nvim-telescope/telescope.nvim'},},}
      
require('neoclip').setup({
      keys = {
        telescope = {
          i = {
            select = '<cr>',
            paste = '<c-p>',
            paste_behind = '<c-o>',
          },
        },
      }
})

```

when i hit enter within telescope, it gets put into my "0 register. I'd like it instead for me to be able to just hit p and paste the entry i selected. Is this possible?

**Comment by AckslD** [comment]
You can also press `<c-p>` in insert mode or `p` in normal mode to do this by default, ie instead of `<cr>`
