### ISSUE TITLE
How to paste like P?

### ISSUE THREAD

**Issue by danielo515** [AckslD/nvim-neoclip.lua#106]
Hello, and thank you for this great plugin, is a life saver.
I wonder how can I paste like `P`, which is what I'm used to do when using normal neovim. Usually I put the cursor, and when selecta en entry in neoclip, it always end after the text I want, as opposed of right before.
To give you an example:

I want this line (cursor is just before the `;`):
```
      let subtitles = inlineSubtitles;
```
To become:
```
      let subtitles = inlineSubtitles->inlineSubtitlesToString;
```
But what I get  instead is:
```
      let subtitles = inlineSubtitles;->inlineSubtitlesToString
```
In normal vim I will just use P, but in neoclip, even  after setting <cr> as paste-behind I still get the undesired behaviour.
Is there a way? Thanks in advance!

**Comment by AckslD** [comment]
Maybe this is the same as #96?

**Comment by danielo515** [comment]
Yes, is exactly the same issue. Sorry.
