### ISSUE TITLE
Record yanks through a Lua command/function

### ISSUE THREAD

**Issue by maxigaz** [AckslD/nvim-neoclip.lua#114]
I'm using Neovim v0.9.5 and I have two Lua helper functions (one for LaTeX, and one for Typst files) that parses the current line and if it finds markup for a table row, it yanks content from certain cells.

Yanking is done with the following command, built into Neovim:

```lua
vim.fn.setreg('"', 'some text example')
```

When one of the functions is run, currently the content is placed in register `"`, but not in Neoclip's history. (Other than that, pressing `y{count` in normal mode works as intended.) Is it possible to make it also appear in Neoclip?

**Comment by AckslD** [comment]
`neoclip` relies on events, in particular the `TextYankPost` which is not triggered when calling `setreg`. 

You could either do this by actually doing a yank, eg `vim.cmd.normal("yy")`. Or by manually adding the entry with eg
```lua
require('neoclip.storage').insert({
  regtype='c',
  contents='some text example',
  filetype='tex',
}, 'yanks')
```
Note that this is an internal function but I don't expect it to change.

**Comment by maxigaz** [comment]
> `neoclip` relies on events, in particular the `TextYankPost` which is not triggered when calling `setreg`.
> 
> You could either do this by actually doing a yank, eg `vim.cmd.normal("yy")`. Or by manually adding the entry with eg
> 
> ```lua
> require('neoclip.storage').insert({
>   regtype='c',
>   contents='some text example',
>   filetype='tex',
> }, 'yanks')
> ```
> 
> Note that this is an internal function but I don't expect it to change.

I've just tried running that as an Ex-command in a buffer with a `.tex` file in it:

```
:lua require('neoclip.storage').insert({ regtype='c', contents='some text example', filetype='tex', }, 'yanks')
```

After that, when I bring up Neoclip with `:lua require('telescope').extensions.neoclip.default()`, I get the following error:

```
E5108: Error executing lua .../packer/start/nvim-neoclip.lua/lua/neoclip/telescope.lua:204: bad argument #1 to 'concat' (table expected, got string)
stack traceback:
        [C]: in function 'concat'
        .../packer/start/nvim-neoclip.lua/lua/neoclip/telescope.lua:204: in function 'entry_maker'
        ...scope.nvim/lua/telescope/finders/async_static_finder.lua:17: in function 'new_table'
        .../packer/start/nvim-neoclip.lua/lua/neoclip/telescope.lua:290: in function 'default'
        [string ":lua"]:1: in main chunk
```

**Comment by AckslD** [comment]
@maxigaz, sorry my bad, the `contents` should be a table of lines:
```lua
require('neoclip.storage').insert({
  regtype='c',
  contents={'some text example'},
  filetype='tex',
}, 'yanks')
```

**Comment by maxigaz** [comment]
> @maxigaz, sorry my bad

No worries!

> the `contents` should be a table of lines:
> 
> ```lua
> require('neoclip.storage').insert({
>   regtype='c',
>   contents={'some text example'},
>   filetype='tex',
> }, 'yanks')
> ```

It works perfectly, even when it's integrated into my helper functions. Thank you!
