### ISSUE TITLE
Suggestion: Why not using the `require("telescope.builtin").registers()` history

### ISSUE THREAD

**Issue by Zeioth** [AckslD/nvim-neoclip.lua#116]
Telescope has a built in option that does about the same as this plugin. The downside is you don't get a preview.

There is any chance we could use this history instead of sqlite? That would remove the system dependency.

**Comment by AckslD** [comment]
Hi @Zeioth, that doesn't store a history right?

**Comment by Zeioth** [comment]
I was wrong sorry, it only contain the last value of every register.
