### ISSUE TITLE
setup() function to neoclip  gives error

### ISSUE THREAD

**Issue by JoseConseco** [AckslD/nvim-neoclip.lua#12]
I have this error:
![image](https://user-images.githubusercontent.com/13521338/130431997-262430bd-3f96-498e-b9a3-6841a6fe1915.png)
When I use any config inside setup() function  (empty or not -  setup()  always gives above message)

Only using simple config (without setup ) works
```lua
use { "AckslD/nvim-neoclip.lua", after='telescope.nvim',
 config = function() require('nv-neoclip')  end, }   
```
I use lost of other plugins with setup() configs and they work ok.

**Comment by AckslD** [comment]
Thanks for reporting @JoseConseco 

I think it should be `require('neoclip')`?

(on my phone atm, but can check in a little bit if that doesn't work)

**Comment by JoseConseco** [comment]
my bad. I totally forgot I had my config in separate file named 'nv-neoclip'

**Comment by AckslD** [comment]
No problem, glad to hear it's working now :)
