### ISSUE TITLE
Error when reaching neoclip history max site

### ISSUE THREAD

**Issue by JoseConseco** [AckslD/nvim-neoclip.lua#14]
I changed history size to 10 elements. When I yank 11th element i get:
![image](https://user-images.githubusercontent.com/13521338/130468169-d67295ab-855e-412c-9d96-8f6de32c6955.png)

**Comment by AckslD** [comment]
Thanks for reporting @JoseConseco!

I'll check this! Btw, I'm also working on adding a test framework so will add this as a testcase 👍

**Comment by AckslD** [comment]
@JoseConseco should be fixed by #15, let me know if it works for you
