### ISSUE TITLE
[Feature request] OSC52 support

### ISSUE THREAD

**Issue by lcrockett** [AckslD/nvim-neoclip.lua#19]
It would be great if `nvim-neoclip` would support OSC52 based copy support. This allows for a clipboard entry to be copied to the system's clipboard through SSH and makes it much easier to copy / paste across multiple machines via SSH at the same time as it uses the host's system clipboard.

I currently use [ojroques/vimoscyank](https://github.com/ojroques/vim-oscyank) to enable OSC52 support for copying / yanking text which seems to work great. However it doesn't seem to work when yanking a clipboard entry via `nvim-neoclip` using Telescope. Not sure if that should work out of the box though or if code changes within `nvim-neoclip` are required for that to work.

Cheers on the plugin !

**Comment by AckslD** [comment]
Hi @lcrockett! Thanks for the suggestion!

I haven't used vimoscyank myself but it seems like the recommended use is to setup an autocommand for the `TextYankPost` event. The same event is also used by neoclip to store anything that gets yanked. However when one selects an entry from the history using telescope the register is set using `setreg` but this does not trigger `TextYankPost`. This is intended in order for neoclip to not store the entry again in storage.

It's not clear directly how to make neoclip talk to vimooscyank but maybe you have some ideas? One way could be to allow a user to provide a custom function to be called when selecting an entry in the history. What do you think?

**Comment by lcrockett** [comment]
A custom function that can be triggered during selection of an entry sounds like a good option that doesn't change the current workflow as I assumed it would be opt-in ? This way you could leave the current `setreg` functionality intact which seems to be the least intrusive option.

How are you envisioning this custom function trigger ? A standard Lua function that can be specified post-selection perhaps ?

**Comment by AckslD** [comment]
@lcrockett I made an attempt to add this in #24, let me know if it works for you. To call the `oscyank` command in your custom action you can for example do:
```lua
require('neoclip').setup({
  ...
  keys = {
    ...
    n = {
      ...
      custom = {
        ['<space>'] = function(opts)
          local handlers = require('neoclip.handlers')
          -- set the registers with the entry
          handlers.set_registers(opts.register_names, opts.entry)
          -- optionally paste entry
          -- handlers.paste(opts.entry, 'p')
          -- optionally paste entry behind
          -- handlers.paste(opts.entry, 'P')

          -- call osyank
          for register_name in opts.register_names do
            vim.cmd('OSCYankReg ' .. register_name)
          end
        end,
      },
    },
  },
})
```

**Comment by lcrockett** [comment]
Cheers on the change. I've tested it but am unable to use it successfully so far. When hitting `<space>` I get a error, see screenshot below.

![image](https://user-images.githubusercontent.com/58056722/134828037-444d6c1f-44b1-45ae-9cc3-8538dc0cec2f.jpeg)

Also see configuration here below:

```lua
require('neoclip').setup {
  keys = {
    i = {
      custom = {
        ['<space>'] = function(opts)
          local handlers = require('neoclip.handlers')
          -- set the registers with the entry
          handlers.set_registers(opts.register_names, opts.entry)
          -- optionally paste entry
          -- handlers.paste(opts.entry, 'p')
          -- optionally paste entry behind
          -- handlers.paste(opts.entry, 'P')

          -- call osyank
          for register_name in opts.register_names do
            vim.cmd('OSCYankReg ' .. register_name)
          end
        end,
      },
    },
    n = {
      custom = {
        ['<space>'] = function(opts)
          local handlers = require('neoclip.handlers')
          -- set the registers with the entry
          handlers.set_registers(opts.register_names, opts.entry)
          -- optionally paste entry
          -- handlers.paste(opts.entry, 'p')
          -- optionally paste entry behind
          -- handlers.paste(opts.entry, 'P')

          -- call osyank
          for register_name in opts.register_names do
            vim.cmd('OSCYankReg ' .. register_name)
          end
        end,
      },
    },
  },
  on_paste = {
    set_reg = true,
  }
}

require('telescope').load_extension('neoclip')
```

**Comment by AckslD** [comment]
@lcrockett Ah I needs to be
```lua
for _, register_name in ipairs(opts.register_names) do
  vim.cmd('OSCYankReg ' .. register_name)
end
```
Ie with `ipairs` when looping :)

**Comment by AckslD** [comment]
Closing this since #24 is now merged, let me know if you have issues

**Comment by lcrockett** [comment]
Including `ipairs` when looping did the trick, cheers for the change and merge !

**Comment by AckslD** [comment]
Great! :)
