### ISSUE TITLE
.vim support

### ISSUE THREAD

**Issue by NoahRR** [AckslD/nvim-neoclip.lua#25]
LOVE the idea of this plugin. Unfortunately, I can't fully convert to .lua just yet. Is there any way to use this in a .vim neovim setup?

Apologies if this is the wrong place to ask this -- but this is an issue I'm having. Any help would be appreciated!

**Comment by AckslD** [comment]
Hi @NoahRR!

You can wrap the setup of neoclip in:
```vim
lua << EOF
-- your setup
EOF
```

**Comment by AckslD** [comment]
Closing this now, feel free to open a new issue if you still have issues :)

**Comment by NoahRR** [comment]
Hey @AckslD, so sorry for not responding!! Been a busy couple weeks.

I did try wrapping it like mentioned above before, but I'll give it another go when I get a free second. I'll checkout that link you sent as well. Appreciate the reponse!

**Comment by AckslD** [comment]
No problem @NoahRR :) Hope you'll get it working
