### ISSUE TITLE
Possibility to delete one item

### ISSUE THREAD

**Issue by sphynx79** [AckslD/nvim-neoclip.lua#30]
is there one command in telescope windows to delete one registry entry?

Thanks

**Comment by AckslD** [comment]
Hi @sphynx79! That's sounds like it would be a usable functionality :) Could you describe a bit more your usecase, for example would you like to keep the telescope window open after deleting the entry? If the window can close after then it will be quite easy in the current framework but if it should stay open such that you can keep deleting entries then it would require a bit of refactoring of the code.

**Comment by AckslD** [comment]
@sphynx79 This is now implemented in #54 which I'll probably merge in a few days :)
