### ISSUE TITLE
Persistant history with vim-plug and init.vim

### ISSUE THREAD

**Issue by eemax** [AckslD/nvim-neoclip.lua#33]
What is needed to load sqlite with vim-plug?

My init.vim looks like this:
`lua << END
require'neoclip'.setup{
enable_persistant_history = true
}
require'telescope'.load_extension('neoclip')
END
`
My plugins.vim looks like this:
`Plug 'AckslD/nvim-neoclip.lua'
Plug 'tami5/sqlite.lua'`

I tried doing:
`require'neoclip'.load_extension('tami5/sqlite.lua')`
and
`require'neoclip'.load_extension('sqlite')`

Any suggestions how to make them work together with this setup?

**Comment by AckslD** [comment]
Hi @eemax! I don't use vim-plug but I don't think you should have to load sqlite manually at all. If you don't what behaviour are you seeing?

**Comment by eemax** [comment]
Persistent history just doesn't do anything.
It seems like the plugins don't communicate with each other. You mention the following for packer:
```
 "AckslD/nvim-neoclip.lua",
  requires = {'tami5/sqlite.lua', module = 'sqlite'}
```
The equivalent for vim-plug I'm not really sure how to do.

**Comment by AckslD** [comment]
@eemax maybe this is the same as #32?

**Comment by eemax** [comment]
@AckslD that is indeed the issue. Seems like it is still unresolved as a vim-plug issue.

**Comment by AckslD** [comment]
@eemax I'll close this and we can keep the discussion on #32. If you have any ideas what might be breaking with vim-plug feel free to add it there :)
