### ISSUE TITLE
hi, i have some trouble,cloud you help me

### ISSUE THREAD

**Issue by 1096015776** [AckslD/nvim-neoclip.lua#34]
i want to use <c-n> to select next item and <c-p> to select preve item,i read these document, I could not found some config to set the map,clould you help me, please

**Comment by AckslD** [comment]
Hi @1096015776, are you asking how to navigate between rows in the telescope picker? If so, then you should be able to do this with `j`/`k` (normal mode) or arrow keys (normal and insert mode).

**Comment by 1096015776** [comment]
thanks for your answer ，i just wan ro config map some key to change because some plugin i use c-p to select prev item and c-n to select next item，if it is different for others，i feel sad，because i like the plugin

**Comment by AckslD** [comment]
These key mappings are the default ones from telescope so you'd change them in your telescope config. For how to do this see either `:help telescope.defaults.mappings` or https://github.com/nvim-telescope/telescope.nvim#default-mappings.

**Comment by xeluxee** [comment]
I was experiencing the same issue. Solved with this config
``` lua
require('neoclip').setup {
	keys = { telescope = { i = {
		paste = '<nop>',
		paste_behind = '<nop>',
	}}}
}
```

**Comment by AckslD** [comment]
Oh now I understand, thanks for clarifying @xeluxee :)

**Comment by 1096015776** [comment]
thanks for your answer,it let me feel better when i coding.

**Comment by AckslD** [comment]
I'm glad to hear @1096015776 :)
