### ISSUE TITLE
Multiple Register support - specifically  clipboard - not loading in Telescope Preview

### ISSUE THREAD

**Issue by ZacharyRizer** [AckslD/nvim-neoclip.lua#38]
Hi there, 

I can't seem to get this piece of config to function as I would expect - `default_register = {'"', '+', '*'}`.  I was expecting this to populate :Telescope neoclip with everything in those three registers, but I don't see anything form the '+' or '*' registers. Here is my neoclip setup in my init.nvim:

![Screen Shot 2022-01-05 at 9 57 37 AM](https://user-images.githubusercontent.com/5158853/148238665-6ba98907-ac5d-4a30-a3f3-f56634e94b8c.png)

Here is what the :Telescope neoclip shows:

![Screen Shot 2022-01-05 at 9 58 58 AM](https://user-images.githubusercontent.com/5158853/148238888-ec5699ef-295e-4289-89b8-507aeaaabd8b.png)

You can see at the top it is saying 'for registers ", +, *', but I don't see the contents of those last two registers. Here is the content of :registers

![Screen Shot 2022-01-05 at 10 00 09 AM](https://user-images.githubusercontent.com/5158853/148239064-e3352cc1-84d9-4c34-9f15-6662c27eb4df.png)

Any help would be appreciated. Thanks.

**Comment by AckslD** [comment]
Hi @ZacharyRizer! `neoclip` only listens to the `TextYankPost` event for things that are yanked, it doesn't read directly from the registers and specifically doesn't check if eg `"+` changed if you copied something outside neovim. So at least at the moment I think `neoclip` doesn't do what you were hoping, unless I might have misunderstood what you were trying to do.

**Comment by ZacharyRizer** [comment]
@AckslD no you understood perfectly and thank you for the response. If it is possible down the line to have things that were copied outside of Neovim (to the + and * registers) shown in the :Telescope neoclip buffer that woudl be amazing.

**Comment by AckslD** [comment]
@ZacharyRizer That would probably be nice indeed but I think this would maybe require some change to core neovim to for example have events triggered for these things. Cause I would like to avoid having something in `neoclip` continuously checking for changes and rather have it react to something.

**Comment by ZacharyRizer** [comment]
@AckslD thanks again for the response. I am not sure how[ vim-yankstack ](https://github.com/maxbrunsfeld/vim-yankstack) functions, but in that plugin the external clipboard is part of the yanks available to paste inside of neovim. You can see in this screen shot - the first is what I yanked from my browser, and the second two are from within neovim. Not sure how they implement it, but could be useful. Thanks again.

**Comment by AckslD** [comment]
Interesting, thanks for sharing @ZacharyRizer

**Comment by AckslD** [comment]
@ZacharyRizer Does it actually store a history of what was yanked outside neovim? What happens if you copy two different things outside neovim, do you only see the last. Looking at the source code it looks like it only looks up what's currently in eg `"+`.

**Comment by ZacharyRizer** [comment]
It only takes the most recent yank outside neovim. So if you copy two things it will only show the most recent outside neovim. It also looks like it replaces the most recent yank inside neovim with the yank you just took from outside. 

So for instance if I yank two lines in neovim:
![Screen Shot 2022-01-05 at 2 55 31 PM](https://user-images.githubusercontent.com/5158853/148280535-e66d7fd0-9450-4333-bb4e-6ffd8ddd97ca.png)

Then if I yank outside neovim once it looks like it replaces the first instance with the outside yank:
![Screen Shot 2022-01-05 at 2 56 05 PM](https://user-images.githubusercontent.com/5158853/148280635-417b1d65-ff06-4dde-9fe7-75b8b47da398.png)

Then yanking outside neovim again just replaces that with the new yank:
![Screen Shot 2022-01-05 at 2 56 48 PM](https://user-images.githubusercontent.com/5158853/148280731-71b0acd2-e752-4986-a453-ad28060a160b.png)

And then yanking inside neovim again will continue to build the yankstack:
![Screen Shot 2022-01-05 at 2 57 26 PM](https://user-images.githubusercontent.com/5158853/148280812-e49ac1a9-96ca-470e-98bc-725ebc40de3a.png)
