### ISSUE TITLE
don't work with my init.lua

### ISSUE THREAD

**Issue by doums** [AckslD/nvim-neoclip.lua#4]
Hi,

I don't know who is the culprit, but when I try to run `:Telescope neoclip` nothing happen, no telescope window opens.

Here is my [init.lua](https://github.com/doums/dotfiles/blob/master/.config/nvim/init.lua).

I just added
```
require'neoclip'.setup()
```
to my init.lua.

Update: It works when I use `:lua require('telescope').extensions.neoclip.default()`. Maybe there is a problem when the plugin manager is not packer (I use paq).

**Comment by AckslD** [comment]
Hi @doums!

Hmm strange, I never used paq so not sure how it loads plugins. Does it lazy load?

Does it work if you first do
```
require('telescope').load_extension('neoclip')
```
?

**Comment by stephengolub** [comment]
Piling on for more data on this one. I'm using `vim-plug` wrapped inside some lua files. It doesn't load there either, I have to do your `load_extension` example and then it's available (through both the `:lua ...` and `:Telescope ...` commands

**Comment by AckslD** [comment]
Thanks for letting me know @stephengolub! Do you think adding something in the README that in some case one needs to call `load_extension` is enough? We could also expose another function from `neoclip` which does that but not sure it gives anything. I would like to avoid calling the `load_extension` in `setup` to avoid setting up all of `telescope` on startup. I'd rather lazy load it when needed. If you have any further thoughts I'm happy to hear them :)

**Comment by stephengolub** [comment]
Yea, I'd add it to your `README`. I also use [ThePrimeagen/git-worktree.nvim](https://github.com/ThePrimeagen/git-worktree.nvim) and there's a section in there about integrating it with Telescope.

So maybe add it to your **Tips** section or create a **Troubleshooting** section?

**Comment by doums** [comment]
Hi @AckslD,

I confirm it's work if I load the extension first
```
require('telescope').load_extension('neoclip')
```
