### ISSUE TITLE
I need help, cannot see history in :Telescope neoclip

### ISSUE THREAD

**Issue by throwaway69420-69420** [AckslD/nvim-neoclip.lua#43]
I cannot see history in :Telescope neoclip even after yanking some lines
here is my telescope.lua config

https://gist.github.com/throwaway69420-69420/5a5b41b9102b4a2277f385596e3fb085

I am using packer.nvim btw

**Comment by AckslD** [comment]
Hi @throwaway69420-69420, are you calling
```lua
require('neoclip').setup()
```
in your setup?

**Comment by throwaway69420-69420** [comment]
@AckslD 
nope, where do I need to add this in
`  use { "AckslD/nvim-neoclip.lua",  -- for neovim clipboard history
  requires = {
     {'nvim-telescope/telescope.nvim'},
    },
  }
`
can you please give me the edited part of the code?

**Comment by throwaway69420-69420** [comment]
update: I added the line in the plugins.lua and it works now

thanks for the help

**Comment by throwaway69420-69420** [comment]
btw I am new at using plugins
what does 
`require('neoclip').setup()`
do?

**Comment by AckslD** [comment]
Good that it works now :)

Most plugins written in lua have a `setup` function you need to call to initialize the plugin. This usually sets any needed keybindings/autocmds etc and acts much like vimscript files in a `plugin` folder, but gives more freedom to the user to choose when to initialize the plugin. Useful if you want to fo example lazy load plugins.

In the case of `neoclip` the `setup` simply adds some autocmds which listens to events triggered when you yank. So if you don't call `setup` these are never triggered.

Hope that helps :)

**Comment by throwaway69420-69420** [comment]
thanks :)
