### ISSUE TITLE
Spelling of enable_persistant_history

### ISSUE THREAD

**Issue by pjcj** [AckslD/nvim-neoclip.lua#44]
I suppose that `enable_persistant_history` should really be spelt `enable_persistent_history`.

Not a big deal but it shows up as a spelling mistake in my config file :)

**Comment by AckslD** [comment]
Woops haha, thanks for reporting this. I opened #45 as a fix. `enable_persistant_history` is still supported but gives a warning cause I didn't want to break things for others due to this spelling mistake :)

**Comment by pjcj** [comment]
Thank you!
