### ISSUE TITLE
Use cross-platform function for mkdir

### ISSUE THREAD

**Issue by nzbart** [AckslD/nvim-neoclip.lua#50]
Thanks for this great plugin!

I use neoclip on Windows and Linux, and notice that the mkdir command used here doesn't work correctly on Windows, creating a directory called `-p` as well as throwing up an error message.

https://github.com/AckslD/nvim-neoclip.lua/blob/6e5d6dbf242c3c3fd55a3521368808490a86ce62/lua/neoclip/db.lua#L17

Would it be possible to use the built-in Neovim function instead?

```lua
vim.fn.mkdir(dirname(db_path), 'p')
```

**Comment by AckslD** [comment]
Oh right! Thanks for raising this and also providing the solution :)

Would you mind trying out #51 and see if it works for you? I don't have access to windows

**Comment by nzbart** [comment]
@AckslD thanks for fixing this so promptly!
