### ISSUE TITLE
How to select yank from history to current clipboard?

### ISSUE THREAD

**Issue by kdurant** [AckslD/nvim-neoclip.lua#6]

**Comment by AckslD** [comment]
Hi @kdurant! What do you mean by "current clipboard"? Ie is this your system clipboard?

**Comment by kdurant** [comment]
@AckslD 

"current clipboard" is `**` or `"0"`.

**Comment by AckslD** [comment]
Install this plugin and do either
```
Telescope neoclip
```
or
```
lua require('telescope').extensions.neoclip.default()
```
:)

**Comment by joshuarubin** [comment]
I'm having an issue like this too, it might be the same, but the OP didn't specify much.
I have `set clipboard=unnamedplus,unnamed` which means that by default puts come from the `+` and/or `*` registers and not from `"`. As a result, while this plugin does in fact populate `"`, it does not update the value that will be used for the default put operation.
I've tried to run `:Telescope neoclip +` and `:Telescope neoclip *` to no avail, I get this:
```
E5108: Error executing lua ...ig/nvim/plugged/telescope.nvim/lua/telescope/command.lua:168: attempt to call a nil value
```
Ideally, this plugin would recognize the value of `clipboard` and do things properly automatically. Failing that, there should at least be a way to specify the `+` or `*` registers in the command.

Thanks for the great tool, it's super useful and I hope this can get fixed!

**Comment by JoseConseco** [comment]
I think something broke (maybe after updating telescope).  I'm also unable to select  item from neoclip list with `ret` key.  Instead of selecting entry and putting it into " register, now neoclip just open new buffer on `ret` key when selecting yank item...

**Comment by AckslD** [comment]
Thanks for reporting @joshuarubin @JoseConseco! I'll look into this hopefully soon but might be little time cause I'm travelling atm.

Good news is that I added preview of yanks in telescope and ability to paste an entry directly without populating a register. Will push that when I get the chance :)
