### ISSUE TITLE
Telescope which_key shows <anonymous> instead of action

### ISSUE THREAD

**Issue by drybalka** [AckslD/nvim-neoclip.lua#64]
Telescope has a useful feature to show mappings on <?> or <C-/> (internally called telescope.actions.which_key). However, for neoclip it shows <anonymous> instead of actions (for example, paste or paste_previous) and prints an error "No name available for anonymous functions". It would be great if this worked as intended.

**Comment by AckslD** [comment]
Sounds good @drybalka! Do you know how to set those names or where that is documented :)

**Comment by AckslD** [comment]
Oh it uses the name of the function? That's a bit weird, do you know if it's possible to provide an explicit separate name for it instead? I think the code is a bit cleaner without assigning the functions to variables.

Thanks for the PR!

**Comment by drybalka** [comment]
Works for me, and the code is indeed cleaner this way =) Thanks!

**Comment by AckslD** [comment]
Thanks for checking, I made another change cause I realised that the keybinds were actually not working. Instead I made them now a metatable which seems to work for both the action and the names.
