### ISSUE TITLE
Ignoring default_register setting

### ISSUE THREAD

**Issue by magidc** [AckslD/nvim-neoclip.lua#75]
Hi. I am trying to config neoclip to use register "+" as default. I am doing this because this is my default  for paste function as I want to be integrated with systems clipboard.
In spite of setting neoclip config as " default_register = '+'", when selecting a new item from Telescope, the selection is still loaded into " register.

**Comment by AckslD** [comment]
Hi @magidc, this does work for me, could you share your config and how you call neoclip.

**Comment by magidc** [comment]
Here is my neovim [config](https://github.com/magidc/nvim-config).
I call `Telescope neoclip` and select the item, but the item is not loaded to default register "+" (see my neoclip [config](https://github.com/magidc/nvim-config/blob/master/lua/plugins/configs/neoclip.lua))

**Comment by AckslD** [comment]
Hmm, what does the telescope prompt say? Does it say:
```
Pick new entry for registers +
```
or
```
Pick new entry for registers "
```
?

Also does `Telescope neoclip plus`/`Telescope neoclip default`/`Telescope neoclip unnamed` work as expected?

**Comment by magidc** [comment]
Good one!
`Telescope neoclip` says `Pick new entry for registers "`, however if I open it as `Telescope neoclip plus`, all works as I required. This solves my problem but still, if I open telescope without an specific register, shouldn't use the one that was set by default in the configuration?

**Comment by magidc** [comment]
By the way, `Telescope neoclip default` still show `Pick new entry for registers "`

**Comment by magidc** [comment]
Hi, I have eventually solve the issue. It was a race condition.
I was loading telescope extension from telescope's config file. This process happens before neoclip setups with my custom config. In the end, the extension loaded in telescope is the one with default configs

**Comment by AckslD** [comment]
I see, good that you found what was happening :) I'll close this then

**Comment by magidc** [comment]
Vielen dank!!

**Comment by AckslD** [comment]
Are you german hehe? I'm not btw 🙃🇸🇪

**Comment by magidc** [comment]
Oh, sorry. For some reason I though you were German, I am Spanish :laughing: 
Tack!!
