### ISSUE TITLE
FZF picker broken

### ISSUE THREAD

**Issue by barrett-ruth** [AckslD/nvim-neoclip.lua#78]
`nvim --version`:
NVIM v0.8.0-dev-1092-g89b9eab63

Configuration:
```lua
require 'neoclip'.setup()
```
It seems to me that with the newest fzf-lua updates nvim-neoclip is not compatible. Attempting to run:
```lua
require 'neoclip.fzf'()
```

Yields
E5108: Error executing lua ...ite/pack/paqs/start/nvim-neoclip.lua/lua/neoclip/fzf.lua
:127: ...e/nvim/site/pack/paqs/start/fzf-lua/lua/fzf-lua/core.lua:111: attempt to inde
x local 'opts' (a function value)
stack traceback:
        [builtin#36]: at 0x555f1bcce2f0
        ...ite/pack/paqs/start/nvim-neoclip.lua/lua/neoclip/fzf.lua:127: in function <
...ite/pack/paqs/start/nvim-neoclip.lua/lua/neoclip/fzf.lua:105>
        [string ":lua"]:1: in main chunk

**Comment by AckslD** [comment]
Thanks for reporting! Do you know if there were any breaking changes lately in fzf-lua?

**Comment by ibhagwan** [comment]
#79 should fix this.
