### ISSUE TITLE
fzf-lua list not updating after first open

### ISSUE THREAD

**Issue by abidibo** [AckslD/nvim-neoclip.lua#80]
Hi,
this is my problem:
- start neovim
- yank stuff
- launch `lua require('neoclip.fzf')()`
- I can see yanked stuff
- close the fzf-lua preview window
- yank other stuff
- launch `lua require('neoclip.fzf')()`
- only the previous yanked items are present, the list is not updated

If I run `print(vim.inspect(require('neoclip.storage').get()))` I can see al updated entries.

My config:

```
Plug 'AckslD/nvim-neoclip.lua'

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" nvim-neoclip
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
lua require'neoclip'.setup{
            \ requires = { 'ibhagwan/fzf-lua' },
            \ continuous_sync = true,
      \ }

nnoremap <space>y <cmd>lua require('neoclip.fzf')()<CR>
```

I've just updated all plugins, so I should have all updated versions of both fzf-lua and nvim-neoclip.lua

Thanks!

**Comment by AckslD** [comment]
Thanks for reporting! Maybe @ibhagwan might directly know what is going on here? I'm soon travelling so not sure I'll be able to try this myself in the near term unfortunately.

**Comment by ibhagwan** [comment]
@abidibo, https://github.com/AckslD/nvim-neoclip.lua/pull/81 should solve it, before this gets merged you can try it using [my fork](https://github.com/ibhagwan/nvim-neoclip.lua).

@AckslD, few notes:
- Not sure how this worked before as the call to `require('neoclip.storage').get().yanks` was done once at the top of the file, perhaps in the past yanks was a reference that didn't change but this needed to be re-acquired each call to `require('neoclip.fzf')()`
- I also updated the previewe code to use the object's `extend` method (cleaner IMO) and removed the line numbering from the preview window, can easily be reverted by deleting the `Previewer:gen_opts` method or changing L83 to `false`.

**Comment by abidibo** [comment]
@AckslD, @ibhagwan thank you very much. I can confirm the fork is working properly. I wont close the issue sicne you probably will do it after merging.
