### ISSUE TITLE
I cannot get custom key mappings to work

### ISSUE THREAD

**Issue by benwoodward** [AckslD/nvim-neoclip.lua#82]
Here are my configs: 
packages.lua:
https://github.com/benwoodward/dotfiles/blob/db098978c7450be3f8aa2bb633fcf8a16d2cfcd5/.config/nvim/lua/plugins/packages.lua#L111
telescope settings:
https://github.com/benwoodward/dotfiles/blob/db098978c7450be3f8aa2bb633fcf8a16d2cfcd5/.config/nvim/lua/plugins/telescope.lua

By moving `nvim-neoclip` into the `required =` section of `telescope` in `packages.lua` I was able to get `<c-j>` and `<c-k>` to work (my default mappings in `telescope`. However, the custom mappings I'm passing to `neoclip` via the `keys.telescope` object aren't working. I've tried putting them in the `.setup()` function call in `packages.lua` and tried putting them in `extensions.neoclip` in `telescope.lua` and neither work.

I've also tried invoking the plugin via `:Telescope neoclip` and `:lua require('telescope').extensions.neoclip.default()` and the problem remains regardless.

EDIT: this commit fixed it and I'm not entirely sure what the change was, perhaps removing the `extensions.fzf` in `telescope` settings? https://github.com/benwoodward/dotfiles/commit/83d70ad5f75fac0c1794b0cdf33e6b226afc5be6#diff-a7c8b0c146c5006d5e6e1e5347d3992a5acae22b62d08bed0f751d201a9d65aa

**Comment by AckslD** [comment]
Not sure what the issue was but happy it works now 👍
