### ISSUE TITLE
Allow fzf-lua prompt variable

### ISSUE THREAD

**Issue by barrett-ruth** [AckslD/nvim-neoclip.lua#83]
Minor nitpick, but after the recent fix with fzf-lua, I am stuck with a prompt of "Prompt" plus an icon my font cannot render.

Both telescope and fzf-lua allow setting this variable so if you could somehow pass in opts to `require('neoclip').setup()` that would be nice.

**Comment by AckslD** [comment]
Sounds good @barrett-ruth! I'm travelling at the moment so won't implement this but feel free to submit a PR :)
