### ISSUE TITLE
[feature request]: move yanked text to bottom of list on paste

### ISSUE THREAD

**Issue by benwoodward** [AckslD/nvim-neoclip.lua#85]
It'd be great if there was an option to move a yank back to the most recent position in the list on paste. 

Here's the same feature in Alfred: 

<img width="570" alt="image" src="https://user-images.githubusercontent.com/1472981/192207282-6416aca3-85b4-4cee-88a6-762d42ef37ba.png">

and in Raycast:

<img width="312" alt="image" src="https://user-images.githubusercontent.com/1472981/192207436-e430503e-ad10-4785-816c-992c5ef2703a.png">

**Comment by benwoodward** [comment]
> Sounds good, would you like to implement that? 

could you give me some pointers on how to approach that? might give it a go.

**Comment by AckslD** [comment]
I'm at the moment travelling but could give you some pointers if you still need them when I'm back :)

**Comment by AckslD** [comment]
Maybe a good starting point is to take a look at how the deletion of an entry is handled:

https://github.com/AckslD/nvim-neoclip.lua/blob/73fd2494b181cdad5dca2be23bfefd6e34621fd2/lua/neoclip/telescope.lua#L193
