### ISSUE TITLE
Telescope doesnt know neoclip command.

### ISSUE THREAD

**Issue by bluebrown** [AckslD/nvim-neoclip.lua#88]
Hi, I followed the documentation, but when I try `:Telescope neoclip`, I get an error because `neoclip` is not a known command to telescope.

Is there some step I am missing? I tried also requiring telescope (I have installed it actually seperately), and also use `after = "telescope.nvim"`, but the command is still not known.

```lua
use {
  "AckslD/nvim-neoclip.lua",
  config = function()
    require('neoclip').setup()
  end,
}
```

**Comment by AckslD** [comment]
Hi @bluebrown, does the [tips](https://github.com/AckslD/nvim-neoclip.lua#tips) or [troubleshoot](https://github.com/AckslD/nvim-neoclip.lua#troubleshooting) sections in the README help?

**Comment by bluebrown** [comment]
Hi @AckslD, thanks for the swift response. Yes, I missed that part in the troubleshooting section. I was already wondering why I don't need to register this as an extension with telescope.

It works with:

```lua
require('telescope').load_extension('neoclip')
```
