### ISSUE TITLE
paste to the wrong place when using telescope

### ISSUE THREAD

**Issue by Martinits** [AckslD/nvim-neoclip.lua#96]
Hello, I think an item selected from `:Telescope neoclip` should be pasted where the cursor is when launching telescope, but it seems not. For exmaple, if I launch telescope with the cursor is at `t` of the word text:
![image](https://user-images.githubusercontent.com/48900241/211972972-b42e4cf8-da59-4897-93d2-8012cf536885.png)
With a word `foo` yanked before:
![image](https://user-images.githubusercontent.com/48900241/211973054-b70f93ab-faaa-40c6-a105-e4879f355f81.png)
After I select to paste `foo` with `<C-P>`, it's like:
![image](https://user-images.githubusercontent.com/48900241/211973164-b6111a17-c513-4225-8bc5-855becc74936.png)
I think it should be like `tfooest` just like you press `p` with the cursor at `t`, but it's not like that in the picture.
Same thing as the `paste_behind` keybinding, it should be like `footest` instead of `tfooest` .
My config:
```
require('neoclip').setup{
    enable_persistent_history = true,
    default_register = '+',
    keys = {
        telescope = {
            i = {
                select = '<CR>',
                paste = '<C-P>',
                paste_behind = '<C-B>',
                replay = '<C-Q>',
                delete = '<C-D>',
                custom = {},
            },
            n = {
                select = '<CR>',
                paste = 'p',
                paste_behind = 'P',
                replay = 'q',
                delete = 'd',
                custom = {},
            },
        },
    },
}
```

**Comment by AckslD** [comment]
Thanks for opening the issue. Hmm strange I can see this as well, but I'm confused why it happens since the paste command basically just calls `""p`, but I wonder if something happens when closing the telescope picker just before.

**Comment by Martinits** [comment]
You are right. From my test, Telescope will strangely move the cursor right one column when it doesn't jump to other places. I'll try report to telescope, thanks!

**Comment by AckslD** [comment]
@Martinits this seems to be fixed now upstream so closing

**Comment by Martinits** [comment]
They've just reverted the PR.........
