### ISSUE TITLE
Feature request: macro to mapping

### ISSUE THREAD

**Issue by Jeansidharta** [AckslD/nvim-neoclip.lua#98]
Hey!

I recently saw a [Reddit comment](https://www.reddit.com/r/neovim/comments/1085spm/comment/j3s3pqd/?utm_source=share&utm_medium=web2x&context=3) in a related plugin talking about converting the weird macro keycodes to something more readable using [vim.fn.keytrans](https://vimhelp.org/builtin.txt.html#keytrans%28%29).

So instead of seeing something like this:  ![image](https://user-images.githubusercontent.com/26410371/212779754-7f4306d1-f450-43ee-a482-cc9c8488639c.png)

You'd see something like this: ![image](https://user-images.githubusercontent.com/26410371/212779789-58da5c56-f06d-4c12-95a6-d1b807f49c24.png)

I thought of adding a new setting (something like `convert_macro_to_keycodes`? Can't think of a good name right now) defaulted to false, which when set, would make this change.

What do you think? As usual, I'd be willing to open a PR for this, if it's desired

**Comment by AckslD** [comment]
Seems like an excellent idea :+1:
